name: RestApi Test

on: [push, pull_request]


jobs:
  linuxbuild:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check pod version
        run: pod --version

      - name: Check swift version
        run: swift --version
      
      - name: Pod install
        run: |
          cd SampleApp/
          pod install